### ISSUE TITLE
虚拟机迁移问题

### ISSUE THREAD

**Issue by juexun** [zstackorg/zstack-utility#11]
EC2模式下，虚拟机从一台主机迁移到另一台主机后，
1） VIP不可用
2）console不可用
3）用console连接虚拟机时，地址栏显示的host地址还是第一台主机的地址

**Comment by youyk** [comment]
2015-05-05 17:14 GMT+08:00 juexun <notifications@github.com>:

> 从一台主机迁移到另一台主机后，
> 1） VIP不可用
> 2）console不可用
> 3）用console连接虚拟机时，地址栏显示的host地址还是第一台主机的地址
>
> —
>

Thank for reporting this issue！


-- 
Yongkang You

**Comment by zxwing** [comment]
fixed in b6fb9b2825ddbb321c1aac06d1b8891898d3fcb5
