### ISSUE TITLE
a feature for tool

### ISSUE THREAD

**Issue by jaywayjayway** [zstackorg/zstack-utility#16]
Hi,Zhang xin and Yong kong :+1: 

cloud you add a tool to show all status of the services...

just like this:
[root@controller ~]# openstack-status 
== Nova services ==
openstack-nova-api:                     active
openstack-nova-cert:                    active
openstack-nova-compute:                 active
openstack-nova-network:                 inactive  (disabled on boot)
openstack-nova-scheduler:               active
openstack-nova-conductor:               active
== Glance services ==
openstack-glance-api:                   active
openstack-glance-registry:              active
== Keystone service ==
openstack-keystone:                     active
== Horizon service ==
openstack-dashboard:                    active
== neutron services ==
neutron-server:                         active
neutron-dhcp-agent:                     inactive  (disabled on boot)
neutron-l3-agent:                       inactive  (disabled on boot)
neutron-metadata-agent:                 inactive  (disabled on boot)
neutron-lbaas-agent:                    inactive  (disabled on boot)
neutron-openvswitch-agent:              active
== Cinder services ==
openstack-cinder-api:                   active
openstack-cinder-scheduler:             active
openstack-cinder-volume:                inactive  (disabled on boot)
openstack-cinder-backup:                inactive  (disabled on boot)
== Ceilometer services ==
openstack-ceilometer-api:               active
openstack-ceilometer-central:           active
openstack-ceilometer-compute:           active
openstack-ceilometer-collector:         active
openstack-ceilometer-alarm-notifier:    active
openstack-ceilometer-alarm-evaluator:   active
openstack-ceilometer-notification:      active
== Support services ==
mysqld:                                 inactive  (disabled on boot)

**Comment by youyk** [comment]
On Tue, Jun 16, 2015 at 2:31 PM, jaywayjayway <notifications@github.com>
wrote:

> Hi,Zhang xin and Yong kong [image: :+1:]
>
> cloud you add a tool to show all status of the services...
>

Hi,

All zstack services are in single process in management node. So if you can
QueryManagementNode successfully, it means all services in that management
node are all alive. If not, it means all services are down in that
management node.

For example, the next command will show there are 2 management nodes are
alive. Before executing the Query command, please login firstly: zstack-cli
LogInByAccount accountName=admin password=password

[root@zstack-02 ~]# zstack-cli QueryManagementNode
2015-06-16 19:50:58,041 DEBUG [apibinding.api] async call[url:
http://localhost:8080/zstack/api/, request:
{"org.zstack.header.managementnode.APIQueryManagementNodeMsg": {"session":
{"uuid": "673667f9c4c34dd3ac22075cebd80225"}, "conditions": []}}]
{
    "inventories": [
        {
            "heartBeat": "Jun 16, 2015 7:50:56 PM",
            "hostName": "10.10.2.11",
            "joinDate": "Jun 16, 2015 12:42:33 PM",
            "uuid": "988f805354384b23ba23b3de0d724b4b"
        },
        {
            "heartBeat": "Jun 16, 2015 7:50:56 PM",
            "hostName": "10.10.2.10",
            "joinDate": "Jun 16, 2015 5:31:28 PM",
            "uuid": "d7c77c63c7894a8a8afb09bce2283586"
        }
    ],
    "success": true
}


-- 
Yongkang You

**Comment by youyk** [comment]
now, zstack-ctl status will show both zstack management node and ui status
