### ISSUE TITLE
install-zstack.sh's option '-I ' bug 

### ISSUE THREAD

**Issue by jaywayjayway** [zstackorg/zstack-utility#2]
line 1028  for  install-zstack.sh

 MANAGEMENT_IP=`ip -4 addr | grep $MANAGEMENT_INTERFACE | grep inet | awk '{print $2}' | cut -f1  -d'/'`

if themanagement  interface has multi IPs,   it will occur error!!!

**Comment by youyk** [comment]
Could you help to manually try to run following 3 lines in your system to
see if there is any error?

```
 #please change eth0 to your interface device name
 MANAGEMENT_INFTERFACE=eth0
 MANAGEMENT_IP=`ip -4 addr | grep " ${MANAGEMENT_INTERFACE}: " | grep inet
| awk '{print $2}' | cut -f1 -d'/'`
 echo $MANAGEMENT_IP
```

On Wed, Apr 22, 2015 at 1:57 PM, jaywayjayway <notifications@github.com>
wrote:

> line 1028 for install-zstack.sh
>
> MANAGEMENT_IP=ip -4 addr | grep $MANAGEMENT_INTERFACE | grep inet | awk
> '{print $2}' | cut -f1 -d'/'
>
> if themanagement interface has multi IPs, it will occur error!!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack-utility/issues/2>.
>



-- 
Yongkang You

**Comment by youyk** [comment]
fix: https://github.com/zstackorg/zstack-utility/commit/999fcc40381b8f30b1f63a5ab7df250bde2f662a

**Comment by youyk** [comment]
fixed by : https://github.com/zstackorg/zstack-utility/commit/c024665a3fa797da605e718b8a252de5a5829a9c
