### ISSUE TITLE
KVM host can not migrate on CentOS 7.2

### ISSUE THREAD

**Issue by ghxandsky** [zstackorg/zstack-utility#24]
Since RedHat commit fix [libvirt should forbid doing tunnelled migration with migrateuri using migrateToURI2 api](https://bugzilla.redhat.com/show_bug.cgi?id=1073233),  it makes that migrating vm on CentOS 7.2 will fail. The error log as bellow:

`2016-02-25 14:43:28,203 TRACE [CloudBusImpl2] (pool-3-thread-1) [event received]: {"org.zstack.header.vm.APIMigrateVmEvenpe":{"_name":"key.event.API.API_EVENT"},"apiId":"c018728bec49484fac1639576b331fad","success":false,"error":{"code":"HOST.description":"Failed to migrate vm on hypervisor","details":"failed to migrate vm[uuid:cb8b1db66c3c48cbb83bcb2281a35262] m host[uuid:f1182b8f053d4b92913b65053b0022ec, ip:11.0.5.161] to dest host[ip:11.0.5.160], unable to migrate vm[uuid:cb8b148cbb83bcb2281a35262] to qemu+tcp://11.0.5.160/system, argument unsupported: migration URI is not supported by tunnelled on"},"headers":{"schema":{}},"id":"32cc587334664aeea3dffee464112c03","creatingTime":1456382608197}}`

**Comment by zxwing** [comment]
Fixed in 1.1
