### ISSUE TITLE
Ubuntu 14.04.3 LTS跑最新的zstack 没法正常（有时正常有时不正常）启动vm。

### ISSUE THREAD

**Issue by QiRaining** [zstackorg/zstack-utility#30]
{
  "org.zstack.header.vm.APIStartVmInstanceEvent": {
    "success": false,
    "apiId": "6e26fda2517d4bf9b1031e124351b276",
    "headers": {
      "schema": {}
    },
    "error": {
      "code": "VM.1001",
      "cause": {
        "code": "SYS.1006",
        "description": "An operation failed",
        "details": "failed to execute shell command: \nBR_NAME=br_eth0\nNS_NAME=br_eth0\n\nNS=\"ip netns exec $NS_NAME\"\n\nexit_on_error() {\n    if [ $? -ne 0 ]; then\n        echo \"error on line $1\"\n        exit 1\n    fi\n}\n\neth=`eval $NS ip addr | grep 169.254.169.254 | awk '{print $NF}'`\nmac=`eval $NS ip link show $eth | grep ether | awk '{print $2}'`\nexit_on_error $LINENO\n\nCHAIN_NAME=\"USERDATA-$BR_NAME\"\n\nebtables-save | grep \":$CHAIN_NAME\" > /dev/null\nif [ $? -ne 0 ]; then\n    ebtables -t nat -N $CHAIN_NAME\n    exit_on_error $LINENO\n    ebtables -t nat -I PREROUTING --logical-in $BR_NAME -j $CHAIN_NAME\n    exit_on_error $LINENO\nfi\n\nrule=\"$CHAIN_NAME -p IPv4 --ip-dst 169.254.169.254 -j dnat --to-dst $mac --dnat-target ACCEPT\"\nebtables-save | grep -- \"$rule\" > /dev/null\nif [ $? -ne 0 ]; then\n    ebtables -t nat -I $rule\n    exit_on_error $LINENO\nfi\n\nexit 0\nreturn code: 1\nstdout: error on line \n\nstderr: /bin/sh: 20: ebtables-save: not found\nChain USERDATA-br_eth0 already exists.\n"
      },
      "description": "Unable to start a vm",
      "details": "failed to execute shell command: \nBR_NAME=br_eth0\nNS_NAME=br_eth0\n\nNS=\"ip netns exec $NS_NAME\"\n\nexit_on_error() {\n    if [ $? -ne 0 ]; then\n        echo \"error on line $1\"\n        exit 1\n    fi\n}\n\neth=`eval $NS ip addr | grep 169.254.169.254 | awk '{print $NF}'`\nmac=`eval $NS ip link show $eth | grep ether | awk '{print $2}'`\nexit_on_error $LINENO\n\nCHAIN_NAME=\"USERDATA-$BR_NAME\"\n\nebtables-save | grep \":$CHAIN_NAME\" > /dev/null\nif [ $? -ne 0 ]; then\n    ebtables -t nat -N $CHAIN_NAME\n    exit_on_error $LINENO\n    ebtables -t nat -I PREROUTING --logical-in $BR_NAME -j $CHAIN_NAME\n    exit_on_error $LINENO\nfi\n\nrule=\"$CHAIN_NAME -p IPv4 --ip-dst 169.254.169.254 -j dnat --to-dst $mac --dnat-target ACCEPT\"\nebtables-save | grep -- \"$rule\" > /dev/null\nif [ $? -ne 0 ]; then\n    ebtables -t nat -I $rule\n    exit_on_error $LINENO\nfi\n\nexit 0\nreturn code: 1\nstdout: error on line \n\nstderr: /bin/sh: 20: ebtables-save: not found\nChain USERDATA-br_eth0 already exists.\n"
    },
    "type": {
      "_name": "key.event.API.API_EVENT"
    },
    "id": "643b830d55ab4c3681dafa3c80fb2a46",
    "creatingTime": 1461032560850
  }
}

**Comment by youyk** [comment]
It should be fixed.
