### ISSUE TITLE
zstack-ctl 远程安装node报错

### ISSUE THREAD

**Issue by vitter** [zstackorg/zstack-utility#5]
zstack-ctl install_management_node --remote=192.168.0.10
报错：
msg: No Package matching 'python-pip' found available, installed or updated
系统centos7.1.1503 x86_64  update到最新。
需要到远程node192.168.0.10上先手动
yum install epel-release-7-5.noarch
然后再用zstack-ctl 远程安装即可

**Comment by youyk** [comment]
Thanks for reporting it, vitter. Will check it later.

**Comment by youyk** [comment]
I has been fixed. Thanks for reporting issue.
