### ISSUE TITLE
zstack-cli 中不能解析 管道 | 

### ISSUE THREAD

**Issue by QiRaining** [zstackorg/zstack-utility#69]
![image](https://cloud.githubusercontent.com/assets/13825001/17736871/a00cfaa4-64bc-11e6-8819-0c59fb8dd4cd.png)

1.期望支持管道
2.语法错误时给出提示

**Comment by youyk** [comment]
这个管道要这样用

zstack-cli QueryImage fields=format | jq .inventories[0].format

zstack-cli 里面的 交互界面没有办法嵌套shell的，所以不能在里面做shell的事情。
举个例子，你没有办法在python的交互界面 嵌套shell的，比如你输入 python 后看看。
